### ISSUE TITLE
Load database details/credentials from user input/a text file for more than just individual usability 

### ISSUE THREAD

**Issue by DGKSK8LIFE** [DGKSK8LIFE/News-Article-Templating-System#26]

**Comment by DGKSK8LIFE** [comment]
the plan is to probably ask the user for a filename/use a filename as a command line arg, then just take the database info out of that and use it as an arg for `sql.Open`

**Comment by AlexDvorak** [comment]
Could you put a checklist in the description of what needs to be done?

**Comment by DGKSK8LIFE** [comment]
(can also use yaml file)

**Comment by DGKSK8LIFE** [comment]
I hyperlinked the checklist markdown in the README

**Comment by DGKSK8LIFE** [comment]
implemented a fix by reading YAML key (within a YAML file)
