### ISSUE TITLE
Links on preview page statically links to localhost

### ISSUE THREAD

**Issue by AlexDvorak** [DGKSK8LIFE/News-Article-Templating-System#40]
In `app/views/App/Preview.html:L7` [there is a static link to](https://github.com/DGKSK8LIFE/News-Article-Templating-System/blob/master/app/views/App/Preview.html#L7) localhost as opposed to the more general `/article` without the prefix; which would make it a bug outside of developement, or in developement if the port number is ever changed.

**Comment by DGKSK8LIFE** [comment]
Would probably implement a config file or something for it; not that big of a deal now, but it sort of pertains to #26. Remember, that this is the development version; this isn't deployment ready. Would you be okay with me closing this?

**Comment by DGKSK8LIFE** [comment]
> In `app/views/App/Preview.html:L7` [there is a static link to](https://github.com/DGKSK8LIFE/News-Article-Templating-System/blob/master/app/views/App/Preview.html#L7) localhost as opposed to the more general `/article` without the prefix; which would make it a bug outside of developement, or in developement if the port number is ever changed.

Also with all the current files (excluding `init.db` (database opening string doesn't apply to everyone)); the app works

**Comment by AlexDvorak** [comment]
no, because the proper way to do links that are domain agnostic is by simply changing the href to
```html
<a href=/article/{{ .Id }}/{{ urlquery .Title}}>
```

**Comment by DGKSK8LIFE** [comment]
I have now just pushed a fix. Thank you very much for reporting it.

**Comment by AlexDvorak** [comment]
you can reference issue #s from commits if you would like

**Comment by DGKSK8LIFE** [comment]
ty
